name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test
      - run: npm run build


  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build

      - name: Check for relevant changes
        id: changes
        run: |
          # Compare current commit with previous commit to detect relevant changes
          CHANGED=$(git diff --name-only HEAD~1 HEAD -- src/ package.json dist/ tsconfig.json tsup.config.ts)
          echo "Changed files: $CHANGED"
          if [ -z "$CHANGED" ]; then
            echo "skip_release=true" >> "$GITHUB_OUTPUT"
            echo "No relevant changes detected, skipping release."
          else
            echo "skip_release=false" >> "$GITHUB_OUTPUT"
            echo "Relevant changes detected, proceeding with release."
          fi

      - name: Release
        if: steps.changes.outputs.skip_release == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
